// Package sshconfig contains methods for writing SSH config files
package sshconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	model "github.com/grafviktor/goto/internal/model/host"
	"github.com/grafviktor/goto/internal/utils"
)

// Writer is responsible for writing Host models to SSH config format
type Writer struct {
	filePath string
	logger   iLogger
}

// NewWriter creates a new Writer instance
func NewWriter(filePath string, logger iLogger) *Writer {
	return &Writer{
		filePath: filePath,
		logger:   logger,
	}
}

// WriteToFile writes hosts to $GOTO_HOME/hosts.config
func (w *Writer) WriteToFile(hosts []model.Host) error {
	w.logger.Debug("[SSHCONFIG] Writing %d hosts to %s", len(hosts), w.filePath)

	// Ensure directory exists
	dir := filepath.Dir(w.filePath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		w.logger.Error("[SSHCONFIG] Failed to create directory %s: %v", dir, err)
		return err
	}

	content := w.generateSSHConfig(hosts)

	err := os.WriteFile(w.filePath, []byte(content), 0o600)
	if err != nil {
		w.logger.Error("[SSHCONFIG] Failed to write SSH config file: %v", err)
		return err
	}

	w.logger.Info("[SSHCONFIG] Successfully wrote %d hosts to %s", len(hosts), w.filePath)
	return nil
}

func (w *Writer) generateSSHConfig(hosts []model.Host) string {
	var sb strings.Builder

	sb.WriteString("# Generated by goto application\n")
	sb.WriteString("# This file contains SSH configuration for hosts managed by goto\n")
	sb.WriteString("# This file is not currently used, but it is created for future use\n")
	sb.WriteString("# See migration plan from $GOTO_HOME/hosts.yaml to $GOTO_HOME/hosts.config\n")
	sb.WriteString("# Issue reference https://github.com/grafviktor/goto/issues/110\n")
	sb.WriteString("\n")

	for _, host := range hosts {
		w.writeHostEntry(&sb, host)
	}

	return sb.String()
}

func (w *Writer) writeHostEntry(sb *strings.Builder, host model.Host) {
	// Skip hosts that don't have valid titles
	if utils.StringEmpty(&host.Title) {
		w.logger.Debug("[SSHCONFIG] Skipping host with empty title")
		return
	}

	sb.WriteString(fmt.Sprintf("Host %s\n", host.Title))

	if !utils.StringEmpty(&host.Group) {
		sb.WriteString(fmt.Sprintf("    # GG:GROUP %s\n", host.Group))
	}

	if !utils.StringEmpty(&host.Description) {
		sb.WriteString(fmt.Sprintf("    # GG:DESCRIPTION %s\n", host.Description))
	}

	if !utils.StringEmpty(&host.Address) && !host.IsUserDefinedSSHCommand() {
		sb.WriteString(fmt.Sprintf("    HostName %s\n", host.Address))
	}

	if !utils.StringEmpty(&host.LoginName) {
		sb.WriteString(fmt.Sprintf("    User %s\n", host.LoginName))
	}

	if !utils.StringEmpty(&host.RemotePort) && host.RemotePort != "22" {
		sb.WriteString(fmt.Sprintf("    Port %s\n", host.RemotePort))
	}

	if !utils.StringEmpty(&host.IdentityFilePath) {
		sb.WriteString(fmt.Sprintf("    IdentityFile %s\n", host.IdentityFilePath))
	}

	sb.WriteString("\n")
}
