name: e2e tests
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
          cache: true
      - name: Setup Tools
        run: sudo apt-get update && sudo apt-get install ffmpeg && go install github.com/charmbracelet/vhs@v0.8
      - name: Build Binary
        run: go build -o gg ./cmd/goto/*.go
      - name: Run integration tests
        run: e2e/run.sh
