name: tests
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  unit:
    concurrency:
      group: unit-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        go-version: [1.25.x, 1.26.x]
        os: [ubuntu, windows, macOS]
        include:
          - os: windows
            cgo: 0
          - os: ubuntu
            cgo: 1
          - os: macOS
            cgo: 1
    env:
      OS: ${{ matrix.os }}-latest
      GO: ${{ matrix.go-version }}
      CGO_ENABLED: ${{ matrix.cgo }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Test
        run: |
          # With Go 1.25 and CGO enabled the pipeline hangs. Without CGO enabled "-race" is not supported for Go 1.25.
          if [ "${{ matrix.go-version }}" = "1.25.x" ]; then
            go test       -coverpkg=./internal/... -vet=off -count=1 -coverprofile unit.txt -covermode atomic ./...
          else
            go test -race -coverpkg=./internal/... -vet=off -count=1 -coverprofile unit.txt -covermode atomic ./...
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: unit,${{ matrix.os }},go-${{ matrix.go-version }}
          name: unit
          token: ${{ secrets.CODECOV_TOKEN }}
